version: "3"
services:
  dmrlink:
    image: dmrlink
    restart: always
    ports:
      - 62032:62032/udp
    volumes:
      - /srv/dmr/dmrlink.cfg:/opt/DMRlink/dmrlink.cfg
      - /srv/dmr/confbridge_rules.py:/opt/DMRlink/confbridge_rules.py
      - /srv/dmr/playback_config.py:/opt/DMRlink/playback_config.py
      - /srv/dmr/sub_acl.py:/opt/DMRlink/sub_acl.py

